# Generated by Django 5.1.2 on 2024-10-31 11:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_remove_lesson_link_to_video_course_lessons_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_payment', models.DateTimeField(auto_now_add=True, help_text='Дата создания платежа', verbose_name='Дата оплаты')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Введите сумму оплаты', max_digits=10, verbose_name='Сумма оплаты')),
                ('payment_method', models.CharField(help_text='Выберите метод оплаты', max_length=50, verbose_name='Метод оплаты')),
                ('paid_course', models.ForeignKey(blank=True, help_text='Выберите курс из списка', null=True, on_delete=django.db.models.deletion.CASCADE, to='materials.course', verbose_name='Оплаченный курс')),
                ('paid_lesson', models.ForeignKey(blank=True, help_text='Выберите урок из списка', null=True, on_delete=django.db.models.deletion.CASCADE, to='materials.lesson', verbose_name='Оплаченный урок')),
                ('user', models.ForeignKey(help_text='Выберите пользователя из списка', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Оплата',
                'verbose_name_plural': 'Оплаты',
            },
        ),
    ]
